//Exported using: HydroD V4.10-01 started 11-Feb-2021 10:16:44
// ***********************************************************
DirectionSet1 = DirectionSet(Array(0 deg,90 deg));
// ***********************************************************
FrequencySet1 = FrequencySet(FrequencyTypeFrequency, Array(0.01 rad/s,0.05 rad/s,0.1 rad/s,0.15 rad/s,0.2 rad/s,0.25 rad/s,0.3 rad/s,0.35 rad/s,0.4 rad/s,0.45 rad/s,0.5 rad/s,0.55 rad/s,0.6 rad/s,0.65 rad/s,0.7 rad/s,0.75 rad/s,0.8 rad/s,0.85 rad/s,0.9 rad/s,0.95 rad/s,1 rad/s,1.05 rad/s,1.1 rad/s,1.15 rad/s,1.2 rad/s,1.25 rad/s,1.3 rad/s,1.35 rad/s,1.4 rad/s,1.45 rad/s,1.5 rad/s,1.55 rad/s,1.6 rad/s,1.65 rad/s,1.7 rad/s,1.75 rad/s,1.8 rad/s,1.85 rad/s,1.9 rad/s,1.95 rad/s,2 rad/s,2.1 rad/s,2.2 rad/s,2.25 rad/s,2.3 rad/s,2.4 rad/s,2.5 rad/s,2.6 rad/s,2.7 rad/s,2.8 rad/s,2.9 rad/s,3 rad/s,3.2 rad/s,3.4 rad/s,3.6 rad/s,3.8 rad/s,4 rad/s,4.2 rad/s,4.6 rad/s,5 rad/s));
// ***********************************************************
Location1 = Location();
Location1.setDepth(300 m);
Location1.gravity = 9.80665 m/s^2;
Location1.air().density = 1.226 Kg/m^3;
Location1.air().kinematicViscosity = 1.462e-005 m^2/s;
Location1.water().density = 1025 Kg/m^3;
Location1.water().kinematicViscosity = 1.19e-006 m^2/s;
Location1.seabed().normaldirection = Vector3d(0 m,0 m,1 m);
// ***********************************************************
Condition1 = FrequencyDomain(Location1);
Condition1.waterSurface().directionSet = DirectionSet1;
Condition1.waterSurface().frequencySet = FrequencySet1;
Condition1.water().setNoCurrent();
// ***********************************************************
HydroModel1 = HydroModel(HydroModelFloating);
HydroModel1.setColumnStabilized(false);
HydroModel1.setBaselineZPos(0 m);
HydroModel1.setAPXPos(0 m);
HydroModel1.setFPXPos(100 m);
HydroModel1.clearReportMetaCenterRotationAxisAzim();
HydroModel1.addReportMetaCenterRotationAxisAzim(0 deg);
HydroModel1.addReportMetaCenterRotationAxisAzim(90 deg);
HydroModel1.clearReportHeelTrimCombinations();
HydroModel1.addReportHeelTrimCombination(0 deg, 0 deg);
HydroModel1.clearReportZWaterlines();
HydroModel1.addReportZWaterline(-30 m);
HydroModel1.addReportZWaterline(-29.5 m);
HydroModel1.addReportZWaterline(-29 m);
HydroModel1.addReportZWaterline(-28.5 m);
HydroModel1.addReportZWaterline(-28 m);
HydroModel1.addReportZWaterline(-27.5 m);
HydroModel1.addReportZWaterline(-27 m);
HydroModel1.addReportZWaterline(-26.5 m);
HydroModel1.addReportZWaterline(-26 m);
HydroModel1.addReportZWaterline(-25.5 m);
HydroModel1.addReportZWaterline(-25 m);
HydroModel1.addReportZWaterline(-24.5 m);
HydroModel1.addReportZWaterline(-24 m);
HydroModel1.addReportZWaterline(-23.5 m);
HydroModel1.addReportZWaterline(-23 m);
HydroModel1.addReportZWaterline(-22.5 m);
HydroModel1.addReportZWaterline(-22 m);
HydroModel1.addReportZWaterline(-21.5 m);
HydroModel1.addReportZWaterline(-21 m);
HydroModel1.addReportZWaterline(-20.5 m);
HydroModel1.addReportZWaterline(-20 m);
HydroModel1.addReportZWaterline(-19.5 m);
HydroModel1.addReportZWaterline(-19 m);
HydroModel1.addReportZWaterline(-18.5 m);
HydroModel1.addReportZWaterline(-18 m);
HydroModel1.addReportZWaterline(-17.5 m);
HydroModel1.addReportZWaterline(-17 m);
HydroModel1.addReportZWaterline(-16.5 m);
HydroModel1.addReportZWaterline(-16 m);
HydroModel1.addReportZWaterline(-15.5 m);
HydroModel1.addReportZWaterline(-15 m);
HydroModel1.addReportZWaterline(-14.5 m);
HydroModel1.addReportZWaterline(-14 m);
HydroModel1.addReportZWaterline(-13.5 m);
HydroModel1.addReportZWaterline(-13 m);
HydroModel1.addReportZWaterline(-12.5 m);
HydroModel1.addReportZWaterline(-12 m);
HydroModel1.addReportZWaterline(-11.5 m);
HydroModel1.addReportZWaterline(-11 m);
HydroModel1.addReportZWaterline(-10.5 m);
HydroModel1.addReportZWaterline(-10 m);
HydroModel1.addReportZWaterline(-9.5 m);
HydroModel1.addReportZWaterline(-9 m);
HydroModel1.addReportZWaterline(-8.5 m);
HydroModel1.addReportZWaterline(-8 m);
HydroModel1.addReportZWaterline(-7.5 m);
HydroModel1.addReportZWaterline(-7 m);
HydroModel1.addReportZWaterline(-6.5 m);
HydroModel1.addReportZWaterline(-6 m);
HydroModel1.addReportZWaterline(-5.5 m);
HydroModel1.addReportZWaterline(-5 m);
HydroModel1.addReportZWaterline(-4.5 m);
HydroModel1.addReportZWaterline(-4 m);
HydroModel1.addReportZWaterline(-3.5 m);
HydroModel1.addReportZWaterline(-3 m);
HydroModel1.addReportZWaterline(-2.5 m);
HydroModel1.addReportZWaterline(-2 m);
HydroModel1.addReportZWaterline(-1.5 m);
HydroModel1.addReportZWaterline(-1 m);
HydroModel1.addReportZWaterline(-0.5 m);
HydroModel1.addReportZWaterline(0 m);
HydroModel1.addReportZWaterline(0.5 m);
HydroModel1.addReportZWaterline(1 m);
HydroModel1.addReportZWaterline(1.5 m);
HydroModel1.addReportZWaterline(2 m);
HydroModel1.addReportZWaterline(2.5 m);
HydroModel1.addReportZWaterline(3 m);
HydroModel1.addReportZWaterline(3.5 m);
HydroModel1.addReportZWaterline(4 m);
HydroModel1.addReportZWaterline(4.5 m);
HydroModel1.addReportZWaterline(5 m);
HydroModel1.addReportZWaterline(5.5 m);
HydroModel1.addReportZWaterline(6 m);
HydroModel1.addReportZWaterline(6.5 m);
HydroModel1.addReportZWaterline(7 m);
HydroModel1.addReportZWaterline(7.5 m);
HydroModel1.addReportZWaterline(8 m);
HydroModel1.addReportZWaterline(8.5 m);
HydroModel1.addReportZWaterline(9 m);
HydroModel1.addReportZWaterline(9.5 m);
HydroModel1.addReportZWaterline(10 m);
HydroModel1.addReportZWaterline(10.5 m);
HydroModel1.addReportZWaterline(11 m);
HydroModel1.addReportZWaterline(11.5 m);
HydroModel1.addReportZWaterline(12 m);
HydroModel1.addReportZWaterline(12.5 m);
HydroModel1.addReportZWaterline(13 m);
HydroModel1.addReportZWaterline(13.5 m);
HydroModel1.addReportZWaterline(14 m);
HydroModel1.addReportZWaterline(14.5 m);
HydroModel1.addReportZWaterline(15 m);
HydroModel1.addReportZWaterline(15.5 m);
HydroModel1.addReportZWaterline(16 m);
HydroModel1.addReportZWaterline(16.5 m);
HydroModel1.addReportZWaterline(17 m);
HydroModel1.addReportZWaterline(17.5 m);
HydroModel1.addReportZWaterline(18 m);
HydroModel1.addReportZWaterline(18.5 m);
HydroModel1.addReportZWaterline(19 m);
HydroModel1.addReportZWaterline(19.5 m);
HydroModel1.addReportZWaterline(20 m);
HydroModel1.setKidTag("ab296aad-4f98-40cc-abf9-6a904feb83d6");
// ***********************************************************
PanelModel1 = PanelModel(HydroModel1, ElementEnumsFEMFile, "../../../../T1.FEM", true, false);
PanelModel1.setKidTag("54ce38a3-fca3-4902-91ba-aa663b52b411");
// ***********************************************************
LoadingCondition1 = LoadingCondition(HydroModel1, -16 m, 0 deg, 0 deg);
LoadingCondition1.setByDraft(false);
LoadingCondition1.interpolateDampingMatrices(false);
LoadingCondition1.addDampingMatricesToWadam(true);
LoadingCondition1.setKidTag("1c2b70d7-6e14-4754-8c1f-fb62f525d44a");
// ***********************************************************
CrDampingMatix1_1 = AdditionalCriticalDampingMatrix(LoadingCondition1);
CrDampingMatix1_1.setTranslationalTerm(1, 1, 0.08);
CrDampingMatix1_1.setTranslationalTerm(2, 2, 0.08);
CrDampingMatix1_1.setTranslationalTerm(3, 3, 0.06);
CrDampingMatix1_1.setRotationalTerm(4, 4, 0.05);
CrDampingMatix1_1.setRotationalTerm(5, 5, 0.05);
CrDampingMatix1_1.setRotationalTerm(6, 6, 0.04);
CrDampingMatix1_1.setKidTag("cd002c2d-b9b8-4ce3-b82d-bbf870bca96d");
// ***********************************************************
RestoringMatrix1_1 = AdditionalRestoringMatrix(LoadingCondition1);
RestoringMatrix1_1.setTranslationalTerm(1, 1, 108000 N/m);
RestoringMatrix1_1.setTranslationalTerm(1, 2, 0 N/m);
RestoringMatrix1_1.setTranslationalTerm(1, 3, 0 N/m);
RestoringMatrix1_1.setCoupledTerm(1, 4, 0 N);
RestoringMatrix1_1.setCoupledTerm(1, 5, 0 N);
RestoringMatrix1_1.setCoupledTerm(1, 6, 0 N);
RestoringMatrix1_1.setTranslationalTerm(2, 1, 0 N/m);
RestoringMatrix1_1.setTranslationalTerm(2, 2, 108000 N/m);
RestoringMatrix1_1.setTranslationalTerm(2, 3, 0 N/m);
RestoringMatrix1_1.setCoupledTerm(2, 4, 0 N);
RestoringMatrix1_1.setCoupledTerm(2, 5, 0 N);
RestoringMatrix1_1.setCoupledTerm(2, 6, 0 N);
RestoringMatrix1_1.setTranslationalTerm(3, 1, 0 N/m);
RestoringMatrix1_1.setTranslationalTerm(3, 2, 0 N/m);
RestoringMatrix1_1.setTranslationalTerm(3, 3, 0 N/m);
RestoringMatrix1_1.setCoupledTerm(3, 4, 0 N);
RestoringMatrix1_1.setCoupledTerm(3, 5, 0 N);
RestoringMatrix1_1.setCoupledTerm(3, 6, 0 N);
RestoringMatrix1_1.setCoupledTerm(4, 1, 0 N);
RestoringMatrix1_1.setCoupledTerm(4, 2, 0 N);
RestoringMatrix1_1.setCoupledTerm(4, 3, 0 N);
RestoringMatrix1_1.setRotationalTerm(4, 4, 0 N*m);
RestoringMatrix1_1.setRotationalTerm(4, 5, 0 N*m);
RestoringMatrix1_1.setRotationalTerm(4, 6, 0 N*m);
RestoringMatrix1_1.setCoupledTerm(5, 1, 0 N);
RestoringMatrix1_1.setCoupledTerm(5, 2, 0 N);
RestoringMatrix1_1.setCoupledTerm(5, 3, 0 N);
RestoringMatrix1_1.setRotationalTerm(5, 4, 0 N*m);
RestoringMatrix1_1.setRotationalTerm(5, 5, 0 N*m);
RestoringMatrix1_1.setRotationalTerm(5, 6, 0 N*m);
RestoringMatrix1_1.setCoupledTerm(6, 1, 0 N);
RestoringMatrix1_1.setCoupledTerm(6, 2, 0 N);
RestoringMatrix1_1.setCoupledTerm(6, 3, 0 N);
RestoringMatrix1_1.setRotationalTerm(6, 4, 0 N*m);
RestoringMatrix1_1.setRotationalTerm(6, 5, 0 N*m);
RestoringMatrix1_1.setRotationalTerm(6, 6, 189076000 N*m);
RestoringMatrix1_1.setKidTag("fc3f6d8d-5496-4c6b-8197-702fda740ff6");
// ***********************************************************
MassModel1 = MassModel(LoadingCondition1, MassModelSpecified);
MassModel1.setUserMassCoordinateSystem(GlobalCoordinateSystem);
MassModel1.setTotalMass(10551337.71 Kg);
MassModel1.setCOG(Point(20 m,0 m,-1.137794177 m));
MassModel1.setRadiusGyration(Vector3d(36.8 m,36.8 m,28.8 m));
MassModel1.setSpecificProductInertia(0 m, 0 m, 0 m);
MassModel1.addTankMass(true);
MassModel1.internalDynamics(false);
MassModel1.updateStiffnessWithFreeSurfaceEffect(true);
MassModel1.setKidTag("8bd59787-8b12-4628-8622-05a42935e9ce");
// ***********************************************************
WadamRun1 = WadamRun();
WadamRun1.useMultiBody(false);
WadamRun1.setHydroModel(HydroModel1);
WadamRun1.setLoadingCondition(LoadingCondition1);
WadamRun1.setEnvironmentData(Condition1);
WadamRun1.useSeaState(false);
WadamRun1.useFreeSurfaceIntegral(true);
WadamRun1.useThreeLayerFreeSurfaceModel(false);
WadamRun1.setFreeSurfaceAnnulusSize(500 m);
WadamRun1.dataCheck(false);
WadamRun1.setAnalysisType(WadamRunGlobalResponse);
WadamRun1.calculateDrift(false);
WadamRun1.setDriftForceType(WadamRunUnidirectionalWaves);
WadamRun1.driftByFarFieldIntegration(false);
WadamRun1.waveDriftDamping(false);
WadamRun1.setSolverType(WadamRunDirectSolver);
WadamRun1.setMaxMatrixDimension(5000);
WadamRun1.setSingularityType(WadamRunAnalyticalSingularity);
WadamRun1.setIntegrationType(WadamRunOneNodeGauss);
WadamRun1.setPanelDimensionType(WadamRunMaximumDiagonalPanelDimension);
WadamRun1.removeIrrFrequencies(true);
WadamRun1.setForwardSpeedX(0 m/s);
WadamRun1.setForwardSpeedY(0 m/s);
WadamRun1.saveTempWamitFiles(true);
WadamRun1.stopBeforePotenExecution(false);
WadamRun1.bypassPotenExecution(false);
WadamRun1.stopBeforeFirstForceExecution(false);
WadamRun1.bypassFirstForceExecution(false);
WadamRun1.useWadamMassCalculation(false);
WadamRun1.stopBeforeSecondForceExecution(false);
WadamRun1.bypassSecondForceExecution(false);
WadamRun1.useSaveRestart(false);
WadamRun1.setPrintType(WadamRunNormalPrint);
WadamRun1.setResponseFileType(WadamRunSIFFormatted);
WadamRun1.calculateEigenvalues(true);
WadamRun1.defineGlobalResponseReferencePoint(false);
WadamRun1.setGlobalResponseReferencePoint(Point(0 m,0 m,0 m));
WadamRun1.setWaterlinePanelMethod(WadamRunNoPanelPressureAdjustment);
WadamRun1.setLoadTransferLinearInterpolationXmin(0);
WadamRun1.setLoadTransferLinearInterpolationXmax(0);
WadamRun1.sumFrequencyResults(false);
WadamRun1.differenceFrequencyResults(false);
WadamRun1.setToleranceWaterLine(5);
WadamRun1.setToleranceCOG(5);
WadamRun1.setCharacteristicLength(100 m);
WadamRun1.calculateRollDamping(false);
WadamRun1.specifyOutputDirectory(false, false);
WadamRun1.autoOwerwriteExistingResultFiles(false);
WadamRun1.moveResultFiles(false);
WadamRun1.useRunNameAsPrefix(false);
WadamRun1.setKidTag("1a9d73d6-4367-437c-a7b0-6ba3adc33fe9");
// ***********************************************************
WadamWizard1 = WadamWizard();
WadamWizard1.setModelConfiguration(WadamWorkflowPanelModel);
WadamWizard1.setPanelModelConfiguration(WadamWorkflowElementPanelModel);
WadamWizard1.timeDomain(false);
WadamWizard1.rollDamping = true;
WadamWizard1.stochasticRollDamping = false;
WadamWizard1.loadCrossection = true;
WadamWizard1.loadTransfer = true;
WadamWizard1.tankPressure = false;
WadamWizard1.pressurePanels = true;
WadamWizard1.offbodyPoints = true;
WadamWizard1.secondOrder = false;
WadamWizard1.dampingMatrix = false;
WadamWizard1.criticalDamping = false;
WadamWizard1.restoringMatrix = false;
WadamWizard1.addEditObject(DirectionSet1);
WadamWizard1.addEditObject(FrequencySet1);
WadamWizard1.addEditObject(Location1);
WadamWizard1.addEditObject(Condition1);
WadamWizard1.addEditObject(HydroModel1);
WadamWizard1.addEditObject(PanelModel1);
WadamWizard1.addEditObject(LoadingCondition1);
WadamWizard1.addEditObject(MassModel1);
WadamWizard1.addEditObject(WadamRun1);
WadamWizard1.setKidTag("5d916282-0551-45ea-8f08-4efca4e5e99c");
